### ISSUE TITLE
Guardian Druid Ironfur Usage

### ISSUE THREAD

**Issue by tehmufifnman** [Hemario/Ovale_TankScripts#8]
Ironfur doesn't have charges anymore (hasn't in quite awhile), so I think the references to SpellCharges() seem erroneous.

Multiple uses of Ironfur also stack their effect, so unless healing is needed Ironfur should be suggested.  It should not be waiting to tell you to cast Ironfur until a single stack is about to fall off.

**Comment by Hemario** [comment]
Indeed, the SpellCharges(ironfur) is obsolete, but doesn't really affect anything.

About multiple uses of ironfur. This is kinda up to the tank to decide whether he wants to dump rage into ironfur or into maul. 
The ivy veins guide also mentions this on the rotation page:

> Armor is extremely effective at reducing Physical damage intake, and as a result, having at least 1 stack of Ironfur Icon Ironfur up as often as possible is recommended. Additionally, you will occasionally want to pool your Rage in order to put up multiple stacks of Ironfur for a short period of time to deal with a spike in damage. There is a hard limit to how much Armor can reduce your incoming damage by, at 85%. This is unlikely to be reachable with any real consistency outside of Bristling Fur Icon Bristling Fur, but it is worth noting.

**Comment by tehmufifnman** [comment]
Oh totally - I know all about the mechanics of a Guardian Druid - and I agree, it should be up to the player - but your script takes the direction of Maul always (so maybe make it a toggle or some other solution)

Because of the BuffExpires() call on this line:
`if (IncomingDamage(5 physical=1) and (BuffExpires(ironfur 1) or RageDeficit() <= 20))`

**Comment by Hemario** [comment]
It takes the direction of Maul because I check RageDeficit() <= 20 for both actions. I agree that it can be a bit annoying when you're following the dps rotation and find yourself without rage for the next ironfur cuz you used it on Maul.

What would be an alternative?
* Don't check the BuffExpires(ironfur 1)? Basically ironfur will always light up when we have rage. It is to the player to decide if he uses ironfur or not? Maul will still be proposed when we're about to cap rage.

**Comment by tehmufifnman** [comment]
Maybe a toggle?  If I am tanking raid progression I am never going to use
the DPS rotation.

That or a secondary small box for defensive rotation or something?
